fix :: .env 복사 test

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -20,34 +20,6 @@ jobs:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
 
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v2
-        with:
-          install: true
-
-      - name: Install Docker Compose
-        run: |
-            sudo apt-get update
-            sudo apt-get install -y curl
-            curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
-            sudo chmod +x /usr/local/bin/docker-compose
-            docker-compose --version  # 확인용
-
-      - name: Build and Push Multi-Platform Images
-        run: |
-            docker buildx create --use
-            docker buildx build \
-              --platform linux/amd64,linux/arm64 \
-              --push \
-              -t gisu1102/2025techer:web \
-              -f ./Dockerfile \
-              ./
-            docker buildx build \
-              --platform linux/amd64,linux/arm64 \
-              --push \
-              -t gisu1102/2025techer:nginx \
-              -f ./nginx/Dockerfile \
-              ./nginx
 
 
 
@@ -74,8 +46,8 @@ jobs:
             
             # .env 파일을 GitHub Secrets에서 가져와서 EC2에 복사
             echo "Decoding .env file from GitHub Secrets..."
-            echo "${{ secrets.MY_ENV_FILE }}" | base64 --decode > .env
-            
+            echo "${{ secrets.MY_ENV_FILE }}" | base64 --decode > .env || { echo "Base64 decode failed"; exit 1; }
+            echo ".env file decoded successfully"
             
             # docker-compose-prod.yml 파일을 EC2에 복사
             echo "Copying docker-compose-prod.yml to EC2..."
